name: Frontend CI Pipeline

on:
  # Ejecuta en push o PR hacia develop y main
  push:
    branches: [development]
  pull_request:
    branches: [development]
  workflow_dispatch:

jobs:
  ci:
    name: Lint, Type Check, Test & Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      # 1️⃣ Clonar el repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Instalar Node y cachear dependencias
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Linter (ESLint)
      - name: Run ESLint
        run: npm run lint

      # 5️⃣ Chequeo de tipos TypeScript
      - name: TypeScript type check
        run: npx tsc --noEmit

      # 6️⃣ Tests
      - name: Run tests
        run: npm run tests

      # 7️⃣ Build
      - name: Build project
        run: npm run build

env:
  CI: true
  NODE_ENV: test
